[package]
name = "async-timeout"
version = "0.1.0"
authors = ["owen-d <ow.diehl@gmail.com>"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
